pipeline {
    agent any

    environment {
        IMAGE_NAME = 'library-management'
        CONTAINER_NAME = 'library-management-container'
        PORT_MAPPING = '8085:80'  // Update if needed
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/Vaishnavi2003-ECE/Library-Management-Sys.git'
            }
        }

    stage('Build') {
            steps {
                dir('LibraryManagement') {
                     bat 'dotnet build LibraryManagement.csproj'
            }
        }
     }

        stage('Build Docker Image') {
            steps {
                bat "docker build -t library-management ."
            }
        }

        stage('Stop and Remove Old Container') {
            steps {
                bat '''
                docker stop aspnet-mvc-container || exit 0
                docker rm aspnet-mvc-container || exit 0
                '''
            }
        }

        stage('Run New Container') {
            steps {
                bat "docker run -d -p 8085:80 --name library-management-container library-management"
            }
        }
    }
}
